### PR TITLE
Mobile Fixes 1 - Home page heading blurb

### PR DESCRIPTION
**Pull request by wizhaaa**
# Summary

- fix the homepage blurb styling

### CODE REVIEW

**Comment by mly32** [comment]
One issue:

image

the banner background is repeating. probably turn that off (do a fit content for background or change the size)

also, we probably have to update the CI pipeline so that it points to the right backend

image

**Review by mly32 — CHANGES_REQUESTED** [review]
banner background is repeating

**Comment by wizhaaa** [comment]
> banner background is repeating

I think I fixed this now. 

I believe the frontend is just that you have to change the `.env` so that it points to the `-prod` instead of `-staging` link. The CI files looks like it just points to environment variable?

**Comment by wizhaaa** [comment]
JK for the preview link the backend link has to be updated

**Comment by wizhaaa** [comment]
> One issue:
> 
> image
> 
> the banner background is repeating. probably turn that off (do a fit content for background or change the size)
> 
> also, we probably have to update the CI pipeline so that it points to the right backend
> 
> image

But I can't change it either lol

**Review by mly32 — APPROVED** [review]
LGTM!

A small thing (optional to change): the "Learn. Aspire. Create." text overlaps the picture text of "Human Ecology Building". Either move the text down or shift the background up or right so the human ecology building doesn't show in mobile.

image

**Comment by wizhaaa** [comment]
> https://designatcornell--pr107-mobile-fixes-wz-kk53wm6k.web.app

Nice catch, I just swapped the background photo to better match the Figma.

**Pull request merged**
