### PR TITLE
Remove components

### PR DESCRIPTION
**Pull request by Sydney-tran**
### Summary

This PR removes the frontend components our team decided not to include for the MVP launch.

Components removed:
- Course page: Design course quiz, Saved courses button, Bookmark on the card, Bookmark on modal
- Major & Minors page: Majors & minors quiz
- Student Orgs page: Saved student orgs button, Bookmark on the card

### CODE REVIEW

**Review by syoung212 — COMMENTED** [review]
Your PR looks great, I think you did a good job in removing the majority of the larger components we talked about in our subteam meeting! I think something that may require a minor change is that since the quiz button component, as well as the quiz text, is no longer there, there seems to be a large gap between the explore courses and the filter areas. I think editing the height of the TitleContainer component should work. In addition, I am not sure if this is necessary or not and may require conversation during the meeting, but the footer includes components that we will not need, such as the saved section and the designer database, so it could be deleted as well (but I would ask Katrina first!). Besides that, everything looks good!

**Review by katrina433 — COMMENTED** [review]
This is good, we are getting the components clean and ready for launch! Can you also remove the Sort option in Explore Courses and Student Orgs page? Thanks!

**Comment by pratyush1712** [comment]
The changes seem good. The website looks nice. You made sure that removing the components does not mess up the website's design. It is also consistent over all the pages. You could definitely consider removing the components mentioned by Katrina and Sarah. Otherwise, it's great!

**Review by pratyush1712 — COMMENTED** [review]
The changes seem good. The website looks nice. You made sure that removing the components does not mess up the website's design. It is also consistent over all the pages. You could definitely consider removing the components mentioned by Katrina and Sarah. Otherwise, it's great!

**Review by katrina433 — APPROVED** [review]
This looks good, great work!

**Pull request merged**
