### PR TITLE
Mobile header

### PR DESCRIPTION
**Pull request by mly32**
### Summary 

- Adds mobile header view (no transitions/animations).
- Uses isMobileView global state. See header and footer for example.
- Changes pagination component.
- Updated routes and page names (TODO add images in PR writeup to show)

### current header

image

image

image

### improved header

image

image

### initial header
image

image

image

### Breaking Changes 

- Changed nav description for "Student Organizations" to "Student Orgs" (the size made desktop view have bad behavior/spacing).
- Replaced pagination component.
- Only using one logo for both mobile and desktop header.

### CODE REVIEW

**Review by Sydney-tran — COMMENTED** [review]
This pr looks really good! The mobile version of the header and footer are extremely well done! The only thing I noticed was currently on [http://design.cornell.edu/](url), when you navigate to each page, the header indicates which page the user is currently on by making the page name green rather than black.
For example:
Screen Shot 2022-11-06 at 10 37 29 PM
For the pr, I noticed that the page names are only green when hovering over them, and the current page the user is on isn't indicated. 
For example:
Screen Shot 2022-11-06 at 10 37 40 PM
I think it could be useful to keep an indicator of the current page for the user (I noticed it is done for the mobile version of the header). We could also ask the designers what they think/if it's necessary. But besides that, amazing job!

**Review by wizhaaa — COMMENTED** [review]
I agree with that Syndey said about highlighting the current page in the menu. 

There is also this breakpoint here: (~920px or so)
image

Where the Articles link is not visible but instead gets cut off. The breakpoint (at least for the header) should be so that it shows the mobile menu as soon as any links get cut off. 

Also, I like that you added animations to the drop-down but they do look a bit off. It looks like it creates space for the entire drop-down menu and then fades down into it, but that creates an awkward white space for the duration of the animation. If it were to also fade down and push the page's header space (ie. the yellow background on explore pages), it would work perfectly. 

So, if you are able to make the animation more smooth such that it pushes the content down as it fades down rather than allocating awkward white space and then fading down into the allocated white space. Otherwise, it might be better to just animate it (or try using basic CSS fade down animation rather than Semantic UI's).

**Comment by mly32** [comment]
Thanks for the feedback!

I'll fix the overflow for the articles page and update the current page indicator for desktop view.

I agree; the animation for the dropdown looks very weird. I was playing around with it, and semantic-UI's stuff seems to bug out if the components are not from their library. I think for this PR, I will turn off the animation.

Animations can probably be added in a separate PR.

**Review by wizhaaa — APPROVED** [review]
Thanks for making the changes! Looks good to merge except maybe add a Home link too to the drop-down menu?

**Comment by mly32** [comment]
@notwz added home link. also made some breaking changes, so I'll need a re-review.

I ended up cleaning some of the routes (see changed files) and simplifying the home page code / link names.

let me know if these changes should be reverted.

**Comment by wizhaaa** [comment]
Looks fine so far. Just have to remove the Cornell logos now 😔

**Pull request merged**
